site_name: MEFS Odoo User Guide & Docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight

nav:
  - Home: index.md
  - HR:
      - Create Employee Order: sales/create_sales_order.md
      - Create Employee Contract: sales/create_sales_order.md
  - Sales:
      - Create Sales Order: sales/create_sales_order.md
      
  - Project Management
  - Procurement
